[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "panic-stderr"
publish = false
version = "0.0.0-alpha.0"

[dependencies]
linux-io = { path = "../linux-io" }
linux-sys = { path = "../linux-sys" }
ufmt = "0.1.0-beta.4"
heapless = "0.5.0-alpha.2"
