[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "linux-io"
publish = false
version = "0.0.0-alpha.0"

[dependencies]
cty = "0.2.0"
linux-sys = { path = "../linux-sys" }
sc = "0.2.2"
ufmt = "0.1.0-beta.4"
